### ISSUE TITLE
Serata OST sui bad smell

### ISSUE THREAD

**Issue by adellava** [coding-jam/eventi#1]
una serata con un formato OST open space technology ( https://it.wikipedia.org/wiki/Open_Space_Technology ) dove si parla di un tema di interesse comune, io pensavo ai *bad smell* nei progetti a tutto tondo sia tecnici che sociali/organizzativi ( io al tempo l'avevo definita la checklist dell'inculata ma non so se è abbastanza istituzionale). E' un tema adatto perché è ampio, complesso e ci sono  molteplici punti di vista oltre che correlato alle conflittualità che possono emergere nei progetti.

Secondo il format dell'OST si procederà in questo modo:

*1.* il facilitatore illustra il tema (10')
*2.* ogni partecipante propone un tema, un bad smell, di cui vuole parlare e si schedula un tavolo di confronto di 30' all'interno della serata. Io mi immaginavo 3 slot temporali per 3 tavoli che possono lavorare in contemporanea
*3.* lo scopo di ogni tavolo è generare una discussione arrichente oltre che un riassunto su foglio A3 che verrà appeso su una parete (quella vicino al rinfresco)
*4.* mangiamo e beviamo davanti ai riassunti e tutti possono leggere e fare domande. NB chi ha proposto il tema nel punto 2 è l'incaricato di redigere il riassunto e rispondere o indirizzare eventuali richieste di info

lo trovo un buono sia perché è alternativo al solito talk sia perché almeno ci conosciamo meglio e tutti possono portare contenuti

**Comment by francesco-strazzullo** [comment]
Mi piace molto, sia perché avevndo provato il format dell'OST in prima persona so che aiuta tantissimo la conversazione senza dover per forza arrivare ad un risultato. Secondo anche il `bad smell` è un argomento che tutti abbiamo sentito sulla nostra pelle.

**Comment by francesco-strazzullo** [comment]
This issue was moved to m-u-g/eventi#1
