### ISSUE TITLE
The art of composition

### ISSUE THREAD

**Issue by marcosh** [coding-jam/eventi#3]
L'arte di comporre cose ci permette di costruire cose complesse partendo da componenti semplici. Inoltre avere componenti semplici facilmente componibili ci permette di ottenere l'agognata capacità di riutilizzare parti del codice che abbiamo già scritto.

La disciplina che studia e formalizza i meccanismi che regolano la composizione viene chiamata dai matematici "teoria delle categorie".

L'idea sarebbe descrivere le basi di teoria delle categorie e cercare di capire perchè questa può essere rilevante e interessante per un programmatore. Di conseguenza dovranno essere introdotti alcuni concetti di programmazione funzionale, che potrebbero essere esemplificati e testati con un po' di codice.

Sarebbe bello cercare di rendere la serata interattiva, anche se non mi è ancora chiarissimo come...

Una serata del genere potrei gestirla io, oppure si potrebbe provare a contattare Giulio Canti (https://twitter.com/GiulioCanti), che ne sa un sacco di queste cose

**Comment by P3trur0** [comment]
:heart: :heart: oppure Bartosz Milewski :heart:

**Comment by francesco-strazzullo** [comment]
This issue was moved to m-u-g/eventi#2
