### ISSUE TITLE
Types, types everywhere

### ISSUE THREAD

**Issue by marcosh** [coding-jam/eventi#4]
Qualunque linguaggio di programmazione al giorno d'oggi si porta dentro un concetto di "tipi". A seconda del linguaggio però questo concetto assume una valenza ed un'importanza diversa.

L'idea per la serata è di fare un po' di chiarezza su cos'è un tipo, come caratterizzare i vari linguaggi per l'utilizzo che fanno dei tipi e poi cercare di capire fino a che punto i tipi possono essere utili quando di scrive un'applicazione, e quanto invece possono rompere le scatole...

Mi piacerebbe affrontare sia aspetti pratici dell'utilizzo dei tipi, sia le basi teoriche per capire come la teoria dei tipi è in realtà uno strumento fondamentale alla base del ragionamento.

Io penso che mi divertirei un sacco a preparare una serata di questo tipo, da capire quante altre persone oltre a me sono interessante a cose del genere...

**Comment by francesco-strazzullo** [comment]
This issue was moved to m-u-g/eventi#3
