### ISSUE TITLE
Coding Gym

### ISSUE THREAD

**Issue by P3trur0** [coding-jam/eventi#6]
Recentemente ho letto di un'ïnteressante iniziativa che si chiama **Coding Gym**. Ecco qui i riferimenti: [http://coding-gym.org/](http://coding-gym.org/).
L'hanno organizzata anche a Padova e nei prossimi giorni dovrebbero presentarla a Milano.  

Potremmo contattare l'organizzatore, Marco Arena, e chiedegli se ha piacere di farla anche a Treviso oppure se possiamo editarne il format.

**Comment by marcosh** [comment]
ne ha parlato anche alla noslidesconf (https://www.youtube.com/watch?v=6dEcHr6gieM). Purtroppo mi sono perso il suo talk. L'idea comunque mi sembra decisamente interessante! Se poi il format è collaudato diventa anche più facile da mettere in piedi

**Comment by francesco-strazzullo** [comment]
This issue was moved to m-u-g/eventi#4
